### PR TITLE
Christchurch New Zealand

### PR DESCRIPTION
**Pull request by Kvanl**
[trips.txt](https://github.com/mapnificent/mapnificent_cities/files/2873326/trips.txt)
[agency.txt](https://github.com/mapnificent/mapnificent_cities/files/2873327/agency.txt)
[calendar.txt](https://github.com/mapnificent/mapnificent_cities/files/2873328/calendar.txt)
[calendar_dates.txt](https://github.com/mapnificent/mapnificent_cities/files/2873329/calendar_dates.txt)
[routes.txt](https://github.com/mapnificent/mapnificent_cities/files/2873330/routes.txt)
[shapes.txt](https://github.com/mapnificent/mapnificent_cities/files/2873331/shapes.txt)
[stop_times.txt](https://github.com/mapnificent/mapnificent_cities/files/2873332/stop_times.txt)
[stops.txt](https://github.com/mapnificent/mapnificent_cities/files/2873333/stops.txt)

### CODE REVIEW

**Comment by stefanw** [comment]
Hi @Kvanl, thanks for taking the time to get Christchurch on board. You have uploaded the files, but can you also give a link to the source and the terms of use? I tried to find the data on [metroinfo.co.nz](http://www.metroinfo.co.nz/Pages/developer-resource.aspx), but couldn't.

**Comment by Kvanl** [comment]
Hey,

I got the information from this website:
https://transitfeeds.com/p/christchurch-metro/41

But now i found this site too:
https://catalogue.data.govt.nz/dataset?res_format=ZIP&tags=Bus
This is the governmental website. And has many more places with gfts data.
The terms and conditions are here:
https://www.data.govt.nz/terms-of-use/?_gl=1*107aehy*_ga*OTY1NTg3NTMwLjE1NTA1MDg5OTk.*_gid*MTM4NTQ3NDM2LjE1NTA1MDg5OTk
.

It was the first time i uploaded the data. Is this done correctly?


Regards

Koen

**Comment by Kvanl** [comment]
Hi

I was wondering if it was possible to get Christchurch on the map with the
given information?

What do I need to do?

Regards

Koen

**Comment by stefanw** [comment]
Behold: [Mapnificent Christchurch](https://www.mapnificent.net/christchurch/)!

**Comment by Kvanl** [comment]
Super.

Thank you very much.

Koen

**Pull request closed without merging**
