### PR TITLE
Pull request for Windsor, ON

### PR DESCRIPTION
**Pull request by sh4ring4n**
I want to add Windsor, ON

### CODE REVIEW

**Comment by stefanw** [comment]
Thanks! Would it make sense to put the data from Windsor into Detroit? It's two different countries, but the cities are very close. Are there any services (with GTFS files) connecting the two areas?

**Comment by stefanw** [comment]
I put Mapnificent Windsor, ON at this URL for now: https://www.mapnificent.net/windsor-on/

It's hidden on the overview map until we come to a conclusion about merging it with Detroit.

**Comment by sh4ring4n** [comment]
Hi,

Technically yes, because Transit Windsor operates a bus into Detroit.

Raymond.

On Sep 15, 2017 6:07 PM, Stefan Wehrmeyer <notifications@github.com> wrote:

Thanks! Would it make sense to put the data from Windsor into Detroit? It's two different countries, but the cities are very close. Are there any services (with GTFS files) connecting the two areas?

**Comment by sh4ring4n** [comment]
More precisely, the two systems (or three if you include SMART) connects via the tunnel bus. It does require a separate fare (it's included in Windsor's gtfs), and you need a passport (or enhanced driver's license) to cross.

**Pull request merged**
